# config.yaml
defaults:
  # Параметры по умолчанию для всех команд
  school: [10]
  section: ["Механика"]
  

presentation:
  # Настройки для презентаций
  fixed_time:
    formula_ms: 70000
    concept_ms: 100000

pdf:
  # Настройки для PDF
  include_images: false
  include_animations: false